markdown: kramdown
permalink: /:title/
url: https://lifupan.github.io/
name: fupanli
author: Fupan.Li
weichat: lifupan001
email: lifupan@gmail.com
github: lifupan
safe: true
paginate: 20
about: "这里是lifupan个人吐槽的地方，也希望自己把经历过的岁月留下一点痕迹..."
